version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://test_user:test_password@db:5432/warehouse_db?sslmode=disable",
      "up"
    ]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - db

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate

volumes:
  db_data:
